# Generated by Django 4.2.8 on 2025-05-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Backend', '0001_initial'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='like',
        #     unique_together=None,
        # ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
